### ISSUE TITLE
error on start

### ISSUE THREAD

**Issue by frippan** [zewelor/bt-mqtt-gateway#9]
When I try to start with sudo ./gateway.py

I get this error:

Traceback (most recent call last):
  File "./gateway.py", line 13, in <module>
    from config import settings
  File "/home/pi/bt-mqtt-gateway/config.py", line 1, in <module>
    import yaml
ImportError: No module named 'yaml'

**Comment by bbbenji** [comment]
What does `pip3 show pyyaml` output?

Did you do `pip3 install -r requirements.txt`?

You can also try `pip3 install pyyaml`.

**Comment by frippan** [comment]
Quick support :)

pip3 freeze:
APScheduler==3.5.1
bluepy==1.1.4
cryptography==1.7.1
idna==2.2
interruptingcow==0.8
keyring==10.1
keyrings.alt==1.3
paho-mqtt==1.3.1
pyasn1==0.1.9
pycrypto==2.6.1
pygobject==3.22.0
python-apt==1.1.0b5
pytz==2018.4
pyxdg==0.25
PyYAML==3.12
SecretStorage==2.3.1
six==1.11.0
tzlocal==1.5.1

pip3 install -r requirements.txt
did that

pip3 install pyyaml
did not help

**Comment by bbbenji** [comment]
Weird... Try this `sudo python3 gateway.py`

**Comment by frippan** [comment]
Same error, I can try on another computer tomorrow.

**Comment by frippan** [comment]
sudo pip3 install -r requirements.txt

fixed the problem, thanks for the help

**Comment by bbbenji** [comment]
Great, I will update the docs. Thanks.

**Comment by MissingDLL** [comment]
This error still occured to me, seems like the documentation ist not updated yet. I created a pull request.
